version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - php-fpm      
    volumes:
      - web-data:/var/www/html
      
  php-fpm:
    image: php:8-fpm
    volumes:
      - web-data:/var/www/html    
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: mayur
      MYSQL_PASSWORD: password
      
    volumes:
      - db-data:/var/lib/mysql     
  
  phpmyadmin:
    container_name: my-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306      
      
volumes:
  web-data:
  db-data:
